#!/bin/bash
# assign variables
ACTION=${1}
version="1.0.1"
function	show_version()	{

echo	$version
}

function	delete_file()	{

rm	"${1}-12345"
}

function create_file()  {

touch "${1}-12345"
}

function display_help() {
cat << EOF
Usage: ${0} {-v|--version|-d|--delete|-c|--create|-h|--help}  <filename>

OPTIONS:
	-v | --version Show version of the script
	-d | --delete Delete the file
	-c | --Create a new file
	-h | --help Display the command help

Examples:
	-v | --version  Show version of the script
	-d | --delete 	Delete the file
	-c | --create	Create a new file
	-h | --help	Display the command help

Examples:
	Create a new file:
		$ ${0} -c foo.txt

	
	Display help:
		$ ${0} -h

	Delete file:
		$ ${0} -d foo.txt

	Show version:
		$ ${0} -v 
EOF
}

case "$ACTION" in
	-h|--help)
		display_help
		;;
	-c|--create)
		create_file "${2:-server}"
		;;
	-d|--delete)
		delete_file "${2:-server}"
		;;
	-v|--version)
		show_version 
		;;
	*)
	echo "Usage ${0} {-c|-h}"
	exit 1
esac

